### ISSUE TITLE
MATLAB type not supported: missing, (uint32)

### ISSUE THREAD

**Issue by JonMuehlst** [skjerns/mat7.3#11]
Hi, thanks for this very useful library!

Getting the following message while loading a mat file:
`ERROR:root:ERROR: MATLAB type not supported: missing, (uint32)`

I'm assuming this error is minor since I expect any such "missing" fields to translate to "None" values.
Is this assumption valid or completely off?

**Comment by skjerns** [comment]
Can you send me a sample MAT file for debugging? Or any code snippet in MATLAB that produces such values?

**Comment by skjerns** [comment]
Ah, `missing` is a simple type in MATLAB. Yes, this will just default to "None" which I think is appropriate?

**Comment by JonMuehlst** [comment]
Appreciate it, thank you very much.
