### ISSUE TITLE
Load specific variables

### ISSUE THREAD

**Issue by GerardEncina** [skjerns/mat7.3#12]
Add a functionality to allow loading specific variables from the .mat file.

**Comment by skjerns** [comment]
I'll see when I get to it


until then you can probably do something along these lines:

```Python
import h5py
with h5py.File(filename, 'r') as hdf5:
    var = np.array(hdf5['varname'], dtype=$YOURDTYPE)
```

**Comment by skjerns** [comment]
I've implemented it :) feel free to try it out
