### ISSUE TITLE
savemat is possible ?

### ISSUE THREAD

**Issue by hazletee** [skjerns/mat7.3#13]
Hi! Thank you for useful fuction.

I'm using it with great appreciation.
Do you have any plans to create a savemat function?

Thanks.

**Comment by skjerns** [comment]
At this moment I don't have the time for this, sorry.

However, you can just use the scipy-function `scipy.io.savemat` for this.

**Comment by hazletee** [comment]
OK!
Thank you again for the good function.

**Comment by hazletee** [comment]
OK!
Thank you again for the good function.
