### ISSUE TITLE
<HDF5 dataset ..., type "|O"> is not a matlab type

### ISSUE THREAD

**Issue by GillesC** [skjerns/mat7.3#2]
Hi
Thank you for your package. However, when llaoding a v7.3 mat file I got the following error:
```
<HDF5 dataset "Hf": shape (625, 1), type "|O"> is not a matlab type
```

If you could help me in saying what needs to be implemented, I am happy to do a PR.

**Comment by skjerns** [comment]
That happens when there is a MATLAB non standard type. 

Can you upload a sample file with this data type? 

I think I tried to decode those once, but as many of the storage formats are proprietary, it might be very hard to reverse-engineer them. But that depends on the specific type.

**Comment by GillesC** [comment]
Hi skjerns

I think to problem lied with complex numbers.
I stored the real and imaginary part separate, and now it works like a
charm.

**Comment by skjerns** [comment]
that's strange, because it should be able to unpack complex numbers? but good that you found a solution
