### ISSUE TITLE
Add unsqueeze functionality

### ISSUE THREAD

**Issue by pdaude** [skjerns/mat7.3#24]
Hi,
Thanks for you package, it really helps me for loading complex matlab structure in v 7.3. 
Could you add a boolean argument for knowing if array variables have to be squeezed or not.
I already manage to do it with your code but I think this functionality could be of interest for the community.
If necessary, I can do a pull request.

**Comment by skjerns** [comment]
I don't quite understand what exactly you mean by that? To indicate whether squeezing should happen or not?

Feel free to open a PR, including some test cases if possible, thanks!

**Comment by skjerns** [comment]
closed due to inactivity
