### ISSUE TITLE
Support for region references 

### ISSUE THREAD

**Issue by Mitchellb16** [skjerns/mat7.3#27]
Apologies in advance for using python language to describe matlab things. 

I'm having trouble handling structs that have lists of structs in them. To use a spin on your example from documentation: 

```
data_dict = mat73.loadmat('data.mat', use_attrdict=True) 
struct = data_dict['structure'] # assuming a structure was saved in the .mat
```

If structure has 2 fields, 'strings': a list of strings, and 'subvar': a list of structs, this is currently returned by calling struct:

`{'subvar': [{}, {}], 'strings': [None, None]}`

My understanding is hdf5 sees subvar as full of region references. I've worked through this thus far (before I found this package) by: 

```
f = h5py.File(data_dir, 'r')['struct']
ref_1 = f['subvar'][0,0]
ref_2 = f[ref_1]['subvarField'][0][0] 
another_ref = f[ref_2]['subsubvarField']
```
so on and so forth... original code is in a [repo ](https://github.com/Mitchellb16/2pGLM/blob/main/2p_glm.ipynb) I'm working on if this is unclear

**Comment by skjerns** [comment]
Thanks, do you have a sample file for me or some MATLAB code that can create such a structure? 

I can have a look at how to solve this

**Comment by skjerns** [comment]
You can simply remove all data from the structure and replace the rest with dummy values, that should suffice.

Else having a test file would greatly help me, as I don't quite understand what structure you mean

**Comment by skjerns** [comment]
I just tried recreating what you describe, but no luck.

I'm closing this, until you are able to supply a test file
