### ISSUE TITLE
not a MATLAB datatype

### ISSUE THREAD

**Issue by wjyzidane** [skjerns/mat7.3#28]
when I use the mat73.loadmat to load my mat. It gives me the error.

ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "data": shape (46432426,), type "<f8">, (float64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "ir": shape (46432426,), type "<u8">, (uint64)
ERROR:root:ERROR: not a MATLAB datatype: <HDF5 dataset "jc": shape (17488,), type "<u8">, (uint64)

**Comment by skjerns** [comment]
What type is this in MATLAB? If it's a custom type, there is little I can do unfortunately

can you provide a sample file?

**Comment by wjyzidane** [comment]
The sample file is too big to load but I suspect it is a custom type. Thanks for your reply anyway.

**Comment by renatobellotti** [comment]
I think this is a sparse matrix. I have the same issue. You can download an example file from here: https://zenodo.org/record/2708302/files/Protons.zip?download=1

Just unzip the file and try to load the first file.

I tried to create a minimum example, but for some reason it cannot be opened by Python.

MATLAB code:

```matlab
my_mat = sparse([2, 4], [5, 8], [6, 7], 10, 8);
save test.mat my_mat
```
This should create an ``10x8`` sparse matrix where entry (2, 5) is 6 and entry (4, 8) is 8.

I hope this minimum example helps somebody.

**Comment by renatobellotti** [comment]
I figured it out: MATLAB seems to use the compressed sparse columns (CSC) format (see [Wikipedia](https://en.wikipedia.org/wiki/Sparse_matrix)) or the textbook [Iterative Methods for Sparse Linear Systems by Yousef Saad](https://web.stanford.edu/class/cme324/saad.pdf).

This is how you can load them into Python:
```python
import h5py
from scipy.sparse import csc_matrix

f = h5py.File('testv7.3.mat', 'r')
my_mat = f['my_mat']

data = np.array(my_mat['data'])
row_ind = np.array(my_mat['ir'])
col_ind = np.array(my_mat['jc'])

n_rows = my_mat.attrs['MATLAB_sparse']
n_cols = len(col_ind) - 1

arr = csc_matrix((data, row_ind, col_ind), shape=(n_rows, n_cols))
```
This snippet was tested with scipy 1.7, but the doc for 1.8 states that the matrix interface is deprecated and superseded with the new sparse array interface. I don't know which version this project aims to support, but I think this gives you a starting point to include support for sparse matrices.

I'm not 100% sure about finding the number of rows. It seems to work for this case, though.

**Comment by skjerns** [comment]
Thanks alot! For now I will simply use scipy to support sparse matrices. Once they drop support for CSC matrices, I'll think about how to include this.
