### ISSUE TITLE
Load Matlab tables

### ISSUE THREAD

**Issue by peterkorteweg** [skjerns/mat7.3#32]
**Request for feature**: It would be a nice addition if Matlab tables could be imported with mat73. 

Matlab tables are similar to cells and can contain numerical and non-numerical data. 
https://nl.mathworks.com/help/matlab/cell-arrays.html
https://nl.mathworks.com/help/matlab/ref/table.html

The following link may help to explain how tables can be converted:
https://stackoverflow.com/questions/63136526/h5py-issues-to-correctly-read-a-table-class-stored-in-matlab-mat-7-3

Thank you for developing mat73!
Peter

**Comment by skjerns** [comment]
Hey Peter,

When I try creating a table in MATLAB like this

```MATLAB
table_ = table([10;20;30;40], ['a';'b';'c';'d'])
```
It does not let me load the data as mentioned on stackoverflow. Unfortunately it does not seem to work :-/ I'm not sure what is going on or how the data is stored. 

Do you have a sample file for me, e.g. the above mentioned "LUT.mat"?

**Comment by peterkorteweg** [comment]
Hi Simon, 

I do not have access to the mat file from stackoverflow, but here is an example with custom data. On purpose I use much more rows than columns which may help to identify the table.

``` matlab
radio = {'Alfa','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel','India','Juliett','Kilo','Lima','Mike' ...
,'November','Oscar','Papa','Quebec','Romeo','Sierra','Tango','Uniform','Victor','Whiskey','X-ray','Yankee','Zulu'};
cellmat = [num2cell(1:length(radio)); radio]';
tablemat = cell2table(cellmat);
save('radiocell.mat','cellmat');
save('radiotable.mat','tablemat');
```

[example_save_table.zip](https://github.com/skjerns/mat7.3/files/8243383/example_save_table.zip)

**Comment by skjerns** [comment]
Unfortunately I'm not able to load this type of data using the solution proposed in stackoverflow :-/ I'm pretty sure that the data in the answer was not of type `table` but a simple cell or array.

Sorry, it does not look like I can implement this - no idea how to reconstruct the table from the references reliably.

**Comment by peterkorteweg** [comment]
Hi Simon, thank you for giving it a try. Best, Peter
