### ISSUE TITLE
matlab string not supported

### ISSUE THREAD

**Issue by ZhiyanWXZ** [skjerns/mat7.3#35]
I've found some packages handling the .mat files. However, they all can not process the string datatype in Matlab. Because of the large data volume, I can't change the data in Matlab. So, I think if your tool can support more datatype, it'll be more critical.

**Comment by skjerns** [comment]
Please give a minimal reproducable example, so either a MAT file that does not load (just remove everything that works fine and only leave the variable of interest)

**Comment by ZhiyanWXZ** [comment]
I just simply load my .mat file using your tool like this:
`import mat73
data_dict = mat73.loadmat('mydata.mat')`
but the terminal outputs the error message:
`ERROR:root:ERROR: MATLAB type not supported: string, (uint32).`
My .mat file includes the string datatype, and the table in your readme does not contain the string type. So I guess the mat73 does not support string in Matlab.

**Comment by skjerns** [comment]
Usually strings are denoted as `char` arrays MATLAB which gets converted to `str` in Python. Regular strings load just fine, and I know of no other way to create strings.

Could you provide either a sample fine or some code produces a MAT file that gives you the error?

**Comment by skjerns** [comment]
I checked it and the error seems to be due to the new string type introduced in MATLAB, which is no longer using `char` arrays but UTF16 MATLAB® object types. Unfortunately I still don't understand how to decode these using HDF5 :-/ They always appear as a 1x6 UINT16 field, and I don't understand how to extract meaning from them, neither is there any documentation on these object.

Unfortunately there is very little I can do, sorry!

**Comment by skjerns** [comment]
see also https://github.com/h5py/h5py/issues/2077

**Comment by ZhiyanWXZ** [comment]
Thank you for giving me the information. I will learn about it.

**Comment by xiaona123456** [comment]
The problem is still unresolved, isn't it?

**Comment by skjerns** [comment]
> The problem is still unresolved, isn't it?

Nobody has figured out how to solve it yet, no. One would need to reverse-engineer the proprietary format.

**Comment by altair199797** [comment]
wouldn't the simple solution be to convert the string to a char array in matlab, save the file again and then reading works?

**Comment by skjerns** [comment]
Yep that would work.

**Comment by Vindaar** [comment]
I just stumbled on this same problem adding some basic Matlab file reading support to my HDF5 library for Nim https://github.com/Vindaar/nimhdf5.

What a fun situation to be in. Unfortunately, at least in the very near future I won't have time to have a proper look, but I would love to attempt to reverse engineer this. :rofl: If I learn something, I'll keep you updated.
