### ISSUE TITLE
Implement MATLAB datenums to datetime

### ISSUE THREAD

**Issue by miab44** [skjerns/mat7.3#36]
Hi Simon,

Great package, saved me loads of time while working with colleagues who love MATLAB.

I saw that you mentioned something about converting matlab datenums and were looking for method of converting them. If that still is the case, then I often use this function handle matlab datenums --> datetimes.

```
def matlab2datetime(matlab_datenum):
    day = dt.datetime.fromordinal(int(matlab_datenum))
    dayfrac = dt.timedelta(days=matlab_datenum%1) - dt.timedelta(days = 366)
    return day + dayfrac
```

here's an example of how it is implemented:
```
times = [matlab2datetime(tval) for tval in data_dict['time']]
index = pd.to_datetime(times).round('S') # round it, sometimes the times go to weird decimal place
```

**Comment by skjerns** [comment]
Hey @miab44 , thanks for the information!

I looked into this and the `matlab datetime` is saved as a simple float. That means there is no way to differentiate between a `datenum` and a `double` within MATLAB and also not in the resulting file.

I.e.

```MATLAB
test = datenum('26-Feb-2022 12:01:04');
class(test) % => 'double'
```

For this reason, `datenum` is not a datatype, just a data representation and there is no way to implement this - the required information (i.e. "this is a datenum" ) is simply not saved to the file

**Comment by skjerns** [comment]
The type I was looking for is a MATLAB custom type named DateTime, which is something different than datenum. Maybe that's the confusion. Anyway, thanks for the tip!

**Comment by miab44** [comment]
HI Simon,

All good. Looks like I was confused, sorry it couldn't help. I am not too familiar with MATLAB, I mainly find ways to avoid using it. Hence, why I like your package so much :)
