### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RobertXiaobinW** [skjerns/mat7.3#37]
Thank you for your great job.

But I met a problem when I was loading the mat73 lib as follow:
'''
    only_include = [s if s[0]=='/' else f'/{s}' for s in only_include]
                                              ^
SyntaxError: invalid syntax
'''

I didn't change anything, do you know why this happen?

PS: I run it under windows system , anaconda ,and python==3.6

**Comment by skjerns** [comment]
Nope, no idea, that should work. Sure you are running Python 3.6 and not 3.5?
