### ISSUE TITLE
xarray backend to load mat files

### ISSUE THREAD

**Issue by kuchaale** [skjerns/mat7.3#38]
Thanks for the great package. How feasible would it be to add your package as a new backend in [xarrray](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html)? It would allow direct conversion to [other formats](https://docs.xarray.dev/en/stable/user-guide/io.html). In my opinion, it is a pretty [desired functionality](https://stackoverflow.com/questions/72449396/how-to-convert-mat-file-into-netcdf-file-nc-using-python).

**Comment by skjerns** [comment]
I'm sure it is possible, however, I never worked with `xarray` and/or mat-files that would convert to `xarray` formats.

Can you briefly describe to me what the functionality would be that `mat73` would need to offer, or the use case? maybe with some pseudocode?

**Comment by kuchaale** [comment]
[Here](https://github.com/pydata/xarray/discussions/6406) is a short guideline on how to load binary files with a custom backend. Not sure now whether it would be possible to generalize such a backend.

**Comment by skjerns** [comment]
Thanks! 

I'm not sure however if xarray and hdf5 are equivalent enough - as far as I can see only a subset of data types can be converted from hdf5 to xarray. If you give me a special use case it would probably not be difficult to implement it. But coming from a general point and not knowing about xarray and/or how to use xarray, I don't think I' able to do that.

However, feel free to propose something and create a PR :)

**Comment by skjerns** [comment]
btw: `savemat` isn't implemented yet, so the backend wouldn't be able to save anything.

If you give me a sample file that should be able to be opened with xarray and mat73 in combination, I might be able to come up with something

**Comment by kuchaale** [comment]
My use case is like the following:
```python
class MyBackendEntrypoint(BackendEntrypoint):
    def open_dataset(
        self,
        filename_or_obj,
        name,
        drop_variables=None,
    ):
    
        d = loadmat(filename_or_obj, simplify_cells = True)
         
        x = d['x']
        y = d['y']
        time = d['Date']

        return xr.DataArray(
            # Note np.fromfile here
            data=d[name][...,np.newaxis],
            dims=['x','y','time'],
            coords=[
                ('x',x),
                ('y',y),
                ('time', [pd.to_datetime(time, format = '%d-%b-%Y')]),
            ],
        ).to_dataset(name=name)

ds_in = xr.open_dataset(infiles, engine=MyBackendEntrypoint, name="mfx")
ds_in['mfx'].plot()
```
Probably, it is not possible to generalize such a backend since data coordinates may be different from the use case to the use case.

**Comment by skjerns** [comment]
I'm closing this as I probably don't have time to implement it.
