### ISSUE TITLE
support for containers.Map

### ISSUE THREAD

**Issue by wmpauli** [skjerns/mat7.3#42]
**Describe the bug**

Thank you for creating this library. I'm trying to load a mat file that seems to have some sort of dictionary in it as well: 
`namesToIds – map from english label names to class IDs (with C key-value pairs)`

I get the following error:
`__init__ - ERROR: MATLAB type not supported: containers.Map, (uint32)`

Do you have any plans on supporting that type?

update: It's not a pressing issue, as I just realized that another variable as the information I need to construct the map (dictionary) myself.

**Provide sample file**

From https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html:
http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat

**Comment by skjerns** [comment]
I did not download download the file (server only gives me 500kbits), but I suspect that this is another MATLAB custom data type. 

I would happily support these kind of data structures, but unfortunately they are proprietary and I have not starting point of how to decode them :-/
