### ISSUE TITLE
Parsing of character arrays invalidates stored data 

### ISSUE THREAD

**Issue by SumolX** [skjerns/mat7.3#44]
Looking for input as to why the library strips null characters from the original stored character arrays.  We are storing serialized encoded data into character array fields.  We have found the offending line in the code which is manipulating the stored data:

https://github.com/skjerns/mat7.3/blob/master/mat73/core.py#L253

Is there a reason as to why the original data is being altered?  Null characters being replaced with empty characters?  If we were to remove this line, what impacts do you foresee?

Thank You.

**Comment by skjerns** [comment]
Hey @SumolX thanks for raising this issue

I do remember some null chars randomly popping up in the char arrays which were not intended to be there. Do you have a sample MAT file for me for testing?

**Comment by skjerns** [comment]
I looked into it and found the problem as outlined in #45 

I'll make another release with the fix soon.

**Comment by SumolX** [comment]
Excellent, when do you think the next release will be available in order to acquire the library via conda/pip?

**Comment by skjerns** [comment]
should appear any minute.

Via conda probably never, at least I don't uploaded the package there
