### ISSUE TITLE
AttributeError: module 'h5py' has no attribute 'File'

### ISSUE THREAD

**Issue by Ntweat** [skjerns/mat7.3#46]
I keep getting this error whenever I am trying load a mat file

core.py", line 321, in loadmat
    with h5py.File(filename, 'r') as hdf5:
AttributeError: module 'h5py' has no attribute 'File'

**Comment by skjerns** [comment]
Which version of h5py do you have installed?

Your can check by running "pip list" and looking for the package there

**Comment by Ntweat** [comment]
I was able to fix the issue with pip install h5py --upgrade  fresh install
