### ISSUE TITLE
Elements of cell arrays are not loaded when using 'only_include' 

### ISSUE THREAD

**Issue by ethanbb** [skjerns/mat7.3#47]
**Describe the bug**: When selecting variables to load using only_include, entries of cell arrays are not loaded (the cell is included but every entry is 'None'). 

**Provide sample file**: [test_mat73.zip](https://github.com/skjerns/mat7.3/files/11741255/test_mat73.zip)

`mat73.loadmat('test_mat73.mat')`: loads normally.
`mat73.loadmat('test_mat73.mat', only_include='foo')`: results in `[None, None]`

I don't know much about HDF5 files, but I did some debugging and I think what's going on is that entries of a cell are references to variables stored elsewhere in the file, under `/#refs#`. When converting the cell in mat73, the reference is dereferenced properly to get that variable, but when checking whether it should be included, its name is something starting with `/#refs#/` rather than with the name of the parent variable. Thus it is excluded from loading at that stage.

Possible solutions: 
- make a flag to skip the check for inclusion when unpacking a variable, and set it when dereferencing into a cell
- simpler: just return True in `is_included` for anything starting with `/#refs#`. This will not cause the whole `/#refs#` tree to be loaded at the top level, since there's already a check in `mat2dict` that excludes it.

If I were fixing this for myself I would submit it as a PR, but I took your advice and tried pymatreader, which seems to work correctly, so I'll just switch to that for now.

**Comment by skjerns** [comment]
fixed in https://github.com/skjerns/mat7.3/commit/946a59e371c4671113c2a47fec98cc25ead1cadb
