### ISSUE TITLE
data type not supported: dataset, uint32

### ISSUE THREAD

**Issue by saeedtaghipour** [skjerns/mat7.3#5]
```
import mat73
data_dict = mat73.loadmat(DATA_SET_PATH)
```

I get this error:
data type not supported: dataset, uint32

**Comment by skjerns** [comment]
Can you provide me with a sample `.mat` file? uint32 should be no problem.

**Comment by saeedtaghipour** [comment]
my data : https://drive.google.com/file/d/1UsT5U67cCgVswRaPGfXdKO6rfj7abdV5/view?usp=sharing

**Comment by skjerns** [comment]
The variable `regression` is of type `dataset` - this is a custom MATLAB datatype. Although it is similar to `pandas.DataFrame`, it's not quite straight forward to decode this type in python. I haven't looked into it yet, but most other custom datatypes I were unable to decode yet, and MATLAB doesn't specify how they are serialized.

So for now: Change the type of the dataset, e.g. save it as a cell array.
