### ISSUE TITLE
All zero sparse matrices could not be read (with fix)

### ISSUE THREAD

**Issue by SebastiaanBreedveld** [skjerns/mat7.3#56]
All zero sparse matrices fail to be read as no 'data' and 'ir' pointers are stored in the .mat file.

The section in core.py should look like this:

        # sparse elements need to be loaded separately (recursion end)
        # see https://github.com/skjerns/mat7.3/issues/28
        if 'MATLAB_sparse' in hdf5.attrs:
            try:
                from scipy.sparse import csc_matrix
                if 'data' in hdf5:
                    data = hdf5['data']
                    row_ind = hdf5['ir']
                else:
                    data = []
                    row_ind = []
                col_ind = hdf5['jc']
                n_rows = hdf5.attrs['MATLAB_sparse']
                n_cols = len(col_ind) - 1
                return csc_matrix((data, row_ind, col_ind), shape=(n_rows, n_cols))

**Comment by skjerns** [comment]
Thanks for raising the issue, do you want to make a PR including these changes?

**Comment by SebastiaanBreedveld** [comment]
Sure, can you give me a heads-up how to do that from the command line? I tried a "git push" but I do not have access.

**Comment by skjerns** [comment]
You need to create a fork, push to that fork and then you can create a PR

**Comment by SebastiaanBreedveld** [comment]
I think it is out there as request!
