### ISSUE TITLE
structure array is converted to dict of lists rather than list of dict

### ISSUE THREAD

**Issue by jessecusack** [skjerns/mat7.3#6]
Firstly, thanks for making this package it is very handy.

I often work with data that has been stored as a matlab structure array. Currently, mat73 successfully loads this data which is great. However, it is loaded as a dict of lists requiring syntax such as `variable = data["key"][element]`, whereas the matlab syntax would have been `variable = data(element).key;`. The advantage of the latter is that I can easily isolate all variables of a specific element e.g. `data_subset = data(element); variable1 = data_subset.key1; variable2 = data_subset.key2;` etc. Whereas in python, this would require construction of a new dict using a for loop over every key.

Similar functionality to matlab would be achieved by returning list of dict. Do you think it would be easy to modify mat73 to provide this as an option?

**Comment by skjerns** [comment]
Good to hear that the library is used 👍 

As I stopped working with matlab some years ago, I'm unfortunately not so familiar with the syntax, so thanks for letting me know this!

Some clarifications: Is `element` always a numerical index (`int`)? Or can it also be a string?

**Comment by jessecusack** [comment]
In matlab I believe `element` must be of type `int` when working with structure arrays. If I understand correctly a pure struct would be just the limiting cast of a 1x1 size struct array. 

I haven't delved into the details of how matlab types are squashed into hdf5, but I can hazard a guess of how struct arrays work with hdf5. I think they end up as hdf5 group with elements which are all cell arrays - which would explain why your module converts it into a dict of lists.

**Comment by skjerns** [comment]
Hey! I've implemented the changes.

Additionally I changed the default dict to an `AttrDict` that means you can use MATLAB style accessing of structs 👍 

```
d = loadmat('file.mat')
struct = d['struct']
struct[0]['key'] # returns value
struct[0].key  # returns value as well!
```

feel free to try it out from Master, or wait till I uploaded the newest release to pypi.

**Comment by jessecusack** [comment]
Awesome, thank you!
